// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "opensaga/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// SagaPersistingService is an autogenerated mock type for the SagaPersistingService type
type SagaPersistingService struct {
	mock.Mock
}

// Persist provides a mock function with given fields: _a0, _a1
func (_m *SagaPersistingService) Persist(_a0 context.Context, _a1 *dto.SagaCreateDTO) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SagaCreateDTO) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
